<a href="https://colab.research.google.com/github/Bharat41/-data-science-lab-exp01/blob/main/pandas_dataframe2_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas DataFrame Lab - Solutions
Sections A (Easy), B (Moderate), C (Hard)

In [1]:
import pandas as pd
import numpy as np
from io import StringIO

def clip_or_sample(sample_text):
    # Reads from clipboard; falls back to sample text if clipboard is unavailable
    try:
        return pd.read_clipboard()
    except Exception:
        return pd.read_csv(StringIO(sample_text), sep=r"\s{2,}|\t|,", engine="python")

## Section A - Easy

**1. Create `student_df` with Name, Age, City for four students.**

In [2]:
student_df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Karan', 'Neha'],
    'Age': [19, 20, 19, 21],
    'City': ['Mathura', 'Agra', 'Delhi', 'Pune']
})

**2. Display the complete `student_df`.**

In [3]:
student_df

    Name  Age     City
0   Aman   19  Mathura
1   Riya   20     Agra
2  Karan   19    Delhi
3   Neha   21     Pune

**3. Display the column names of `student_df`.**

In [4]:
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

**4. Retrieve the Name column.**

In [5]:
student_df.Name

0     Aman
1     Riya
2    Karan
3     Neha
Name: Name, dtype: object

**5. Retrieve the City column using square brackets.**

In [6]:
student_df['City']

0    Mathura
1       Agra
2      Delhi
3       Pune
Name: City, dtype: object

**6. New DataFrame with only Name and City.**

In [7]:
pd.DataFrame(student_df, columns=['Name', 'City'])

    Name     City
0   Aman  Mathura
1   Riya     Agra
2  Karan    Delhi
3   Neha     Pune

**7. Create `book_df` with Book, Author, Price.**

In [8]:
book_df = pd.DataFrame({
    'Book': ['Python Basics', 'Data Science 101', 'Pandas Guide'],
    'Author': ['A. Sharma', 'R. Verma', 'S. Gupta'],
    'Price': [450, 600, 520]
})
book_df

               Book     Author  Price
0     Python Basics  A. Sharma    450
1  Data Science 101   R. Verma    600
2      Pandas Guide   S. Gupta    520

**8. Add column Publisher with the same value for every row.**

In [9]:
book_df['Publisher'] = 'TechPress'
book_df

               Book     Author  Price  Publisher
0     Python Basics  A. Sharma    450  TechPress
1  Data Science 101   R. Verma    600  TechPress
2      Pandas Guide   S. Gupta    520  TechPress

**9. Five-row DataFrame with `SerialNo` from `np.arange(5)`.**

In [10]:
q9_df = pd.DataFrame({'Item': ['A', 'B', 'C', 'D', 'E']})
q9_df['SerialNo'] = np.arange(5)
q9_df

  Item  SerialNo
0    A         0
1    B         1
2    C         2
3    D         3
4    E         4

**10. Delete the SerialNo column from Question 9's DataFrame.**

In [11]:
del q9_df['SerialNo']
q9_df

  Item
0    A
1    B
2    C
3    D
4    E

**11. Create `movie_df` with Movie, Year, Rating.**

In [12]:
movie_df = pd.DataFrame({
    'Movie': ['Inception', 'Dangal', '3 Idiots'],
    'Year': [2010, 2016, 2009],
    'Rating': [8.8, 8.3, 8.4]
})
movie_df

       Movie  Year  Rating
0  Inception  2010     8.8
1     Dangal  2016     8.3
2   3 Idiots  2009     8.4

**12. New DataFrame from `movie_df` with Movie, Rating and a new column Director (not in original).**

In [13]:
movie_dir_df = pd.DataFrame(movie_df, columns=['Movie', 'Rating', 'Director'])
movie_dir_df

       Movie  Rating  Director
0  Inception     8.8       NaN
1     Dangal     8.3       NaN
2   3 Idiots     8.4       NaN

**13. Series with two city names at indexes 0 and 3.**

In [14]:
city_series = pd.Series(['Delhi', 'Mumbai'], index=[0, 3])
city_series

0     Delhi
3    Mumbai
dtype: object

**14. Assign the Series to a new column Branch in a four-row DataFrame.**

In [15]:
q14_df = pd.DataFrame({'Name': ['P', 'Q', 'R', 'S']})
q14_df['Branch'] = city_series
q14_df

  Name  Branch
0    P   Delhi
1    Q     NaN
2    R     NaN
3    S  Mumbai

**15. Read a copied table into `copied_df` using the clipboard method.**

In [16]:
# Copy a table (e.g. from Excel/webpage) first, then run this cell
copied_df = clip_or_sample('''Name,Marks,Grade
Aman,85,A
Riya,92,A+
Karan,74,B''')
copied_df

    Name  Marks Grade
0   Aman     85     A
1   Riya     92    A+
2  Karan     74     B

## Section B - Moderate

**16. `employee_df` (5 rows); display only Employee and Experience in a new DataFrame.**

In [17]:
employee_df = pd.DataFrame({
    'Employee': ['Amit', 'Sara', 'John', 'Priya', 'Ravi'],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Sales'],
    'Experience': [5, 3, 8, 2, 6]
})
emp_small = pd.DataFrame(employee_df, columns=['Employee', 'Experience'])
emp_small

  Employee  Experience
0     Amit           5
1     Sara           3
2     John           8
3    Priya           2
4     Ravi           6

**17. Retrieve Department, then display all column names.**

In [18]:
print(employee_df['Department'])
employee_df.columns

0         HR
1         IT
2    Finance
3         IT
4      Sales
Name: Department, dtype: object

Index(['Employee', 'Department', 'Experience'], dtype='object')

**18. Add Office = 'Head Office' for every row; display.**

In [19]:
employee_df['Office'] = 'Head Office'
employee_df

  Employee Department  Experience       Office
0     Amit         HR           5  Head Office
1     Sara         IT           3  Head Office
2     John    Finance           8  Head Office
3    Priya         IT           2  Head Office
4     Ravi      Sales           6  Head Office

**19. Replace Office values with `np.arange(5)`.**

In [20]:
employee_df['Office'] = np.arange(5)
employee_df

  Employee Department  Experience  Office
0     Amit         HR           5       0
1     Sara         IT           3       1
2     John    Finance           8       2
3    Priya         IT           2       3
4     Ravi      Sales           6       4

**20. Series `office_names` ('Delhi', 'Mumbai', 'Pune' at indexes 0, 2, 4); assign to Office.**

In [21]:
office_names = pd.Series(['Delhi', 'Mumbai', 'Pune'], index=[0, 2, 4])
employee_df['Office'] = office_names
employee_df

  Employee Department  Experience  Office
0     Amit         HR           5   Delhi
1     Sara         IT           3     NaN
2     John    Finance           8  Mumbai
3    Priya         IT           2     NaN
4     Ravi      Sales           6    Pune

**21. Delete Office and display remaining columns.**

In [22]:
del employee_df['Office']
employee_df.columns

Index(['Employee', 'Department', 'Experience'], dtype='object')

**22. `product_df`; then another DataFrame with columns ordered Price, Product, Category.**

In [23]:
product_df = pd.DataFrame({
    'Product': ['Pen', 'Notebook', 'Bag'],
    'Category': ['Stationery', 'Stationery', 'Accessories'],
    'Price': [10, 50, 700]
})
reordered_df = pd.DataFrame(product_df, columns=['Price', 'Product', 'Category'])
reordered_df

   Price   Product     Category
0     10       Pen   Stationery
1     50  Notebook   Stationery
2    700       Bag  Accessories

**23. Request four columns where one does not exist in source; inspect the missing column.**

In [24]:
source_df = pd.DataFrame({
    'Name': ['A', 'B', 'C'],
    'Age': [20, 21, 22],
    'City': ['X', 'Y', 'Z']
})
new_df = pd.DataFrame(source_df, columns=['Name', 'Age', 'City', 'Country'])
new_df   # the missing 'Country' column is filled with NaN

  Name  Age City  Country
0    A   20    X      NaN
1    B   21    Y      NaN
2    C   22    Z      NaN

**24. Column name with a space (Total Marks); retrieve it.**

In [25]:
marks_df = pd.DataFrame({
    'Student': ['A', 'B', 'C'],
    'Total Marks': [450, 480, 390]
})
marks_df['Total Marks']   # dot notation will not work for names with spaces

0    450
1    480
2    390
Name: Total Marks, dtype: int64

**25. Read a copied table with `pd.read_clipboard()`; show columns; build a 3-column DataFrame.**

In [26]:
clip_df = clip_or_sample('''Name,Dept,Salary,City
Amit,IT,50000,Delhi
Sara,HR,45000,Pune
John,Sales,40000,Mumbai''')
print(clip_df.columns)
clip_sub = pd.DataFrame(clip_df, columns=[clip_df.columns[0], clip_df.columns[1], clip_df.columns[2]])
clip_sub

Index(['Name', 'Dept', 'Salary', 'City'], dtype='object')

   Name   Dept  Salary
0  Amit     IT   50000
1  Sara     HR   45000
2  John  Sales   40000

## Section C - Hard

**26. `course_df`: columns, Student, Student+Score, add Batch.**

In [27]:
course_df = pd.DataFrame({
    'Student': ['Aman', 'Riya', 'Karan', 'Neha', 'Dev'],
    'Course': ['DS', 'ML', 'DS', 'AI', 'ML'],
    'Score': [88, 92, 79, 85, 90]
})
print(course_df.columns)
print(course_df['Student'])
student_score = pd.DataFrame(course_df, columns=['Student', 'Score'])
print(student_score)
course_df['Batch'] = '2029'
course_df

Index(['Student', 'Course', 'Score'], dtype='object')
0     Aman
1     Riya
2    Karan
3     Neha
4      Dev
Name: Student, dtype: object
  Student  Score
0    Aman     88
1    Riya     92
2   Karan     79
3    Neha     85
4     Dev     90

  Student Course  Score Batch
0    Aman     DS     88  2029
1    Riya     ML     92  2029
2   Karan     DS     79  2029
3    Neha     AI     85  2029
4     Dev     ML     90  2029

**27. `travel_df`: Code via `np.arange(5)`, then replace with Series at indexes 1 and 4; display after each.**

In [28]:
travel_df = pd.DataFrame({
    'City': ['Agra', 'Jaipur', 'Goa', 'Shimla', 'Kochi'],
    'Days': [2, 3, 5, 4, 3]
})
travel_df['Code'] = np.arange(5)
print(travel_df)
travel_df['Code'] = pd.Series([101, 104], index=[1, 4])
travel_df

     City  Days  Code
0    Agra     2     0
1  Jaipur     3     1
2     Goa     5     2
3  Shimla     4     3
4   Kochi     3     4

     City  Days   Code
0    Agra     2    NaN
1  Jaipur     3  101.0
2     Goa     5    NaN
3  Shimla     4    NaN
4   Kochi     3  104.0

**28. `school_df`; request Student, Class, Section, House; assign one common House value.**

In [29]:
school_df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Class': [10, 10, 11, 12],
    'Section': ['A', 'B', 'A', 'C']
})
school_house_df = pd.DataFrame(school_df, columns=['Student', 'Class', 'Section', 'House'])
print(school_house_df)   # House is NaN
school_house_df['House'] = 'Blue'
school_house_df

  Student  Class Section  House
0       A     10       A    NaN
1       B     10       B    NaN
2       C     11       A    NaN
3       D     12       C    NaN

  Student  Class Section House
0       A     10       A  Blue
1       B     10       B  Blue
2       C     11       A  Blue
3       D     12       C  Blue

**29. `inventory_df`: partially indexed Series column; display; delete; display again.**

In [30]:
inventory_df = pd.DataFrame({
    'Item': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Quantity': [10, 50, 30, 15],
    'Price': [55000, 500, 1200, 9000]
})
inventory_df['Discount'] = pd.Series([10, 5], index=[0, 2])
print(inventory_df)
del inventory_df['Discount']
inventory_df

       Item  Quantity  Price  Discount
0    Laptop        10  55000      10.0
1     Mouse        50    500       NaN
2  Keyboard        30   1200       5.0
3   Monitor        15   9000       NaN

       Item  Quantity  Price
0    Laptop        10  55000
1     Mouse        50    500
2  Keyboard        30   1200
3   Monitor        15   9000

**30. `lab_df` from a copied 4+ column table; full sequence of operations.**

In [31]:
lab_df = clip_or_sample('''Name,Dept,Total Marks,City
Aman,IT,450,Delhi
Riya,HR,480,Pune
Karan,Sales,390,Mumbai''')
print(lab_df)                                                    # display
print(lab_df.columns)                                            # column names
print(lab_df['Name'])                                            # single-word column
print(lab_df['Total Marks'])                                     # column with a space
small_df = pd.DataFrame(lab_df, columns=['Name', 'Total Marks']) # smaller DataFrame
print(small_df)
lab_df['Status'] = 'Active'                                      # add whole column
print(lab_df)
del lab_df['Status']                                             # delete column
lab_df

    Name   Dept  Total Marks    City
0   Aman     IT          450   Delhi
1   Riya     HR          480    Pune
2  Karan  Sales          390  Mumbai
Index(['Name', 'Dept', 'Total Marks', 'City'], dtype='object')
0     Aman
1     Riya
2    Karan
Name: Name, dtype: object
0    450
1    480
2    390
Name: Total Marks, dtype: int64
    Name  Total Marks
0   Aman          450
1   Riya          480
2  Karan          390
    Name   Dept  Total Marks    City  Status
0   Aman     IT          450   Delhi  Active
1   Riya     HR          480    Pune  Active
2  Karan  Sales          390  Mumbai  Active

    Name   Dept  Total Marks    City
0   Aman     IT          450   Delhi
1   Riya     HR          480    Pune
2  Karan  Sales          390  Mumbai